Feature/7
makingdevs/invoice_automator pull request #8
Opened 2017-12-08 18:48 UTC by marcoreyesc

this branch has mixed changes from feature 4 and 6 plus reading uber-datail functionality

2017-12-08 21:58 UTC, neodevelop requested changes
Por fa, haz estos cambios que te comenté, son menores, sirve que terminamos de probar el flujo de PR...

Gracias

2017-12-08 21:58 UTC, neodevelop commented on src/main/groovy/com/makingdevs/routes/utils/ProcessAttachments.groovy
> +import java.io.InputStream
Quitar los imports que no se usan!!!

2017-12-08 21:58 UTC, neodevelop commented on src/main/groovy/com/makingdevs/routes/utils/ProceessInvoiceDetail.groovy
> +class ProceessInvoiceDetail implements Processor {
Corregir el typo! de _Proceess_

2017-12-08 21:58 UTC, neodevelop commented on src/main/groovy/com/makingdevs/routes/utils/ProceessInvoiceDetail.groovy
> +      detail.put("emitter", emitter[0])
Puedes usar `first()` en lugar de emitter[0]

2017-12-08 21:58 UTC, neodevelop commented on src/main/groovy/com/makingdevs/routes/utils/ProceessInvoiceDetail.groovy
> +      def taxes = xmlParsed[cfdiNs.impuestos][cfdiNs.traslados][cfdiNs.traslado].@importe
No estoy seguro pero creo que lo puedes acceder con ayuda del Namespace

2017-12-11 21:30 UTC, marcoreyesc commented on src/main/groovy/com/makingdevs/routes/utils/ProceessInvoiceDetail.groovy
> +      def taxes = xmlParsed[cfdiNs.impuestos][cfdiNs.traslados][cfdiNs.traslado].@importe
no entiendo que debería hacer, ahí estoy generando una cadena para el mensaje, con las descripciones de los conceptos.

2017-12-11 21:39 UTC, neodevelop approved these changes

2017-12-11 21:40 UTC, neodevelop commented on src/main/groovy/com/makingdevs/routes/utils/ProceessInvoiceDetail.groovy
> +      def taxes = xmlParsed[cfdiNs.impuestos][cfdiNs.traslados][cfdiNs.traslado].@importe
Lo revisamos en vivo!!!

2017-12-11 21:40 UTC, merged